CREATE TABLE USERS(USER_ID INTEGER PRIMARY KEY not null,
   USERNAME VARCHAR(10) not null,
   FIRST_NAME VARCHAR(15),
   MIDDLE_NAME VARCHAR(15),
   LAST_NAME VARCHAR(20),
   PASSWORD VARCHAR(160) not null
);

ALTER TABLE USERS ADD CONSTRAINT UNIQUE_USERNAME UNIQUE(USERNAME);


CREATE TABLE GROUPS
(
   GROUP_ID INTEGER PRIMARY KEY not null,
   GROUP_NAME VARCHAR(20) unique not null,
   GROUP_DESC VARCHAR(200)
);

CREATE TABLE USER_GROUPS
(
   USER_ID INTEGER not null,
   GROUP_ID INTEGER not null,
   PRIMARY KEY (USER_ID,GROUP_ID)
);

ALTER TABLE USER_GROUPS ADD FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);

ALTER TABLE USER_GROUPS ADD FOREIGN KEY (GROUP_ID) REFERENCES GROUPS(GROUP_ID);

INSERT INTO GROUPS (GROUP_ID,GROUP_NAME,GROUP_DESC) VALUES (1,'admin','Administrators');
INSERT INTO GROUPS (GROUP_ID,GROUP_NAME,GROUP_DESC) VALUES (2,'user','Regular users');
